分类指标
boyuai/CS420 pull request #5
Opened 2020-03-10 13:05 UTC by Jun-James

## 分类指标

### 评估指标

|      |      | 预测               | 预测              |
| ---- | ---- | ------------------ | ----------------- |
|      |      | 1                  | 0                 |
| 标签 | 1    | **True  Positive** | False Negative    |
| 标签 | 0    | False Positive     | **True Negative** |

**精度**（Accuracy）:分类正确的样本数占样本总数的比例
$$
\mathrm{Acc}=\frac{\mathrm{TP}+\mathrm{TN}}{\mathrm{TP}+\mathrm{TN}+\mathrm{FP}+\mathrm{FN}}
$$
**准确率**（Precision）:**预测**为1的样本中**标签**为1的比例
$$
\text { Prec }=\frac{\mathrm{TP}}{\mathrm{TP}+\mathrm{FP}}
$$
**召回率**（Recall）:**标签**为1的样本中**预测**为1的比例
$$
\operatorname{Rec}=\frac{\mathrm{TP}}{\mathrm{TP}+\mathrm{FN}}
$$
**问题：准确率和召回率之间如何权衡**？

可以用以下公式来表示二者之间的关系：
$$
\hat{y}=\left\{\begin{array}{ll}
1, & \quad \quad p_{\theta}(y=1 | x)>h \\
0, & \text { otherwise }
\end{array}\right.
$$
$p_{\theta}(y=1 | x)$ 表示在参数为 $\theta$ 的模型参数下，预测为1的样本中，标签为1的概率。

**阈值**[0,1]，越高，代表准确度越高，召回率越低，阈值极端值为0.99

阈值越低，准确度越低，召回率越高，极端情况下，阈值=0

**F1 度量** ：值越大，代表模型表现越佳。
$$
\mathrm{F} 1=\frac{2 \times \text { Precision } \times \mathrm{Recall}}{\text { Precision }+\mathrm{Recall}}
$$
**AUC评价法（ROC（Receiver operating characteristic）曲线下面积）** 

基于排序的度量方法。

可以理解为用描点法，瞄出概率从高到低排列中，每个预测概率下，真正率和假正率组成的的坐标，进而得到ROC曲线，计算其包含的面积后，即可得到AUC值。

![image-20200310162707194](C:\Users\user\AppData\Roaming\Typora\typora-user-images\image-20200310162707194.png)

2020-03-11 02:21 UTC, zhc134 requested changes
请确保markdown能在 https://goessner.github.io/markdown-it-texmath/markdown-it-texmath-demo.html 中正确显示，由于Github不支持渲染公式，我们会使用该工具在网页端渲染。

2020-03-11 03:22 UTC, zhc134 requested changes
有同学提交了一份笔记，请在他的基础上修改哈。https://github.com/boyuai/CS420/blob/master/15_%E5%88%86%E7%B1%BB%E6%8C%87%E6%A0%87_%E8%AF%BE%E5%A0%82%E7%AC%94%E8%AE%B0.md

2020-03-11 03:30 UTC, Jun-James commented
> 请确保markdown能在 https://goessner.github.io/markdown-it-texmath/markdown-it-texmath-demo.html 中正确显示，由于Github不支持渲染公式，我们会使用该工具在网页端渲染。

我已在该网页中正确编辑，谢谢提醒。

2020-03-12 07:57 UTC, zhc134 requested changes
同学你好，目前的笔记依然无法在 [预览工具](https://goessner.github.io/markdown-it-texmath/markdown-it-texmath-demo.html) 中正常渲染。注意markdown with tex中，行间公式的起始 $$ 符号前需要有一个空行，终止 $$ 符号后需要有一个空行。
另外现在已经有同学提交了一份笔记，请在他的文件基础上修改。[15_分类指标_课堂笔记.md](https://github.com/boyuai/CS420/blob/master/15_%E5%88%86%E7%B1%BB%E6%8C%87%E6%A0%87_%E8%AF%BE%E5%A0%82%E7%AC%94%E8%AE%B0.md)
谢谢！

2020-03-12 07:57 UTC, zhc134 commented on 分类指标
> +**准确率**（Precision）:**预测**为1的样本中**标签**为1的比例
```suggestion
**精度**（Accuracy）:分类正确的样本数占样本总数的比例

$$
\mathrm{Acc}=\frac{\mathrm{TP}+\mathrm{TN}}{\mathrm{TP}+\mathrm{TN}+\mathrm{FP}+\mathrm{FN}}
$$

**准确率**（Precision）:**预测**为1的样本中**标签**为1的比例
```

2020-03-12 07:57 UTC, zhc134 commented on 分类指标
> +**准确率**（Precision）:**预测**为1的样本中**标签**为1的比例
同学你好，目前的笔记依然无法在 https://goessner.github.io/markdown-it-texmath/markdown-it-texmath-demo.html 中正常渲染。注意markdown with tex中，行间公式的起始 $$ 符号前需要有一个空行，终止 $$ 符号后需要有一个空行

2020-03-12 14:24 UTC, Jun-James commented on 分类指标
> +**准确率**（Precision）:**预测**为1的样本中**标签**为1的比例
那有点奇怪的，我从提供的编辑器里复制出来的。

2020-03-16 06:48 UTC, closed without merging